### ISSUE TITLE
Luna2 search domain iteration issue

### ISSUE THREAD

**Issue by msteggink** [clustervision/luna2-daemon#6]
When a node is installed with Ubuntu, the search domains aren't written out properly.

Currently we have multiple subdomains in the cluster and they are appended incorrectly in the netplan:

Netplan yaml file:
```
network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      link-local: [ipv6]
      addresses:
        - redacted
      routes:
        - to: default
          via: redacted
          metric: 101
      nameservers:
        search: sub1.domain.com;sub2.domain.com;sub3.domain.com;sub4.domain.com;ipmi;ib
```

Note the correct way to iterate is comma seperated not semicolon. E.g. the output of netplan should be:
```
        search: sub1.domain.com,sub2.domain.com,sub3.domain.com,sub4.domain.com,ipmi,ib
```

resolv.conf output as a result of this:

 search sub1.domain.com**059**sub2.domain.com**059**sub3.domain.com**059**sub4.domain.com**059**ipmi**059**ib

luna cluster
```
| domain_search       | sub1.domain.com,sub2.domain.com,sub3.domain.com,sub4.domain.com,ipmi,ib
```

I assume the issue is written out by `plugins/boot/network/ubuntu.templ`:
```
        search: [{{ DOMAIN_SEARCH }}]
```
